scrape_configs:
  - job_name: 'shelly'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:8080
    scrape_interval: 60s
    params:
      host: ["192.168.0.13"]
      type: ["em"]